vulnerabilities:
  - id: CVE-2026-33186
    paths:
      - usr/local/bin/k6
    statement: Wait for a new K6-Release
    expired_at: 2026-09-01
  - id: CVE-2026-39883
    paths:
      - usr/local/bin/k6
    statement: Wait for a new K6-Release
    expired_at: 2026-09-01
  - id: CVE-2026-35469
    paths:
      - usr/local/bin/k6
    statement: Wait for a new K6-Release
    expired_at: 2026-09-01
  - id: CVE-2026-29181
    paths:
      - usr/local/bin/k6
    statement: Wait for a new K6-Release
    expired_at: 2026-09-01
