sonar.projectKey=steadybit_extension-k6
sonar.organization=steadybit

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out,e2e/e2e-coverage-docker.out

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S8545
sonar.issue.ignore.multicriteria.e1.resourceKey=Dockerfile
